sudo: false
language: python
install: 
        - pip3 install -r requirements.txt -r requirements-extra.txt
script: tox
matrix:
        include:
                - os: "linux"
                  dist: "xenial"
                  python: "3.5"
                - os: "linux"
                  dist: "xenial"
                  python: "3.6"
                - os: "linux"
                  dist: "xenial"
                  python: "3.7"
                - os: "windows"
                  language: shell
                  python: "3.7"
                  env: "PATH=/c/python37:/c/python37/Scripts:$PATH"
                  before_install:
                          - choco install python make
                          - cp /c/python37/python.exe /c/python37/python3.exe
                  before_script:
                          - pip3 install -r requirements-windows.txt
                          - python3 build.py
                  script:
                          - tox -e WINDOWS
